sampleDir: /public1/data/projects/tumor/multi/TCGA/raw/RNA-Seq/BLCA
normalSampleDir: /public1/data/projects/tumor/multi/TCGA/raw/WXS/BLCA
tmpDir: /public1/tmp/lqh
workDir: /home/lqh/Codes/Python/Integrative_Analysis_Bioinformatics_Pipeline/results

cancerType: BLCA
sampleType: Primary_Tumor
cores: 80

samples: /home/lqh/Codes/Python/Integrative_Analysis_Bioinformatics_Pipeline/tables/info/BLCA_RNA_somatic_calling_info.tsv
#folder:
#    WXS_PASS: /home/lqh/Codes/Python/Integrative_Analysis_Bioinformatics_Pipeline/results/LUAD/WXS/WXS_somatic_mutation/SelectVariants/PASS
ref:
    exonInterval: /home/lqh/resources/database/gencode/GRCh38_GENCODE_v22_exon_rm_alt.bed
    targetInterval: /home/lqh/resources/whole_exome_agilent_1.1_refseq_plus_3_boosters.targetIntervals_add_chr_to_hg38_rm_alt.bed
    genome: /public1/data/resources/ref_genome/GRCh38/GRCh38.d1.vd1.fa
    variant:
        dbSNP: /public1/data/resources/ref_variant/hg38/dbsnp_146.hg38.vcf.gz
        kgSNP: /public1/data/resources/ref_variant/hg38/1000G_phase1.snps.high_confidence.hg38.vcf.gz
        kgINDEL: /public1/data/resources/ref_variant/hg38/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
        gnomad: /home/lqh/resources/database/gnomad/af-only-gnomad.hg38.vcf.gz
        gnomad_SNP: /home/lqh/resources/database/gnomad/af-only-gnomad.GRCh38.SNP_biallelic_chr1_AF_mod.vcf.gz
        gnomad_AF: /home/lqh/resources/database/gnomad/af-only-gnomad-AF-more-0.05-chr1-chrY.hg38.vcf.gz
#        PoN: /home/lqh/Codes/Python/Integrative_Analysis_Bioinformatics_Pipeline/results/PoN/WXS_PoN_vcf/all.vcf.gz
#        RNA_PoN: /home/lqh/Codes/Python/Integrative_Analysis_Bioinformatics_Pipeline/results/PoN/LUAD/RNA_PoN_vcf/all.vcf.gz
#        RNA_PoN_TN: /home/lqh/Codes/Python/Integrative_Analysis_Bioinformatics_Pipeline/results/PoN/LUAD/RNA_PoN_vcf_TN/all.vcf.gz
#    RNA_edit_site:
#        DARNED: /home/lqh/resources/database/RNA_edit/DARNED_hg19_to_bed_to_hg38_rm_alt.bed
#        RADAR: /home/lqh/resources/database/RNA_edit/RADAR_Human_AG_all_hg19_v2_to_bed_to_hg38_rm_alt.bed
    annotation:
        gatk_funcotator: /home/lqh/resources/database/gatk/funcotator_dataSources.v1.6.20190124s