# Caution: all files and folders should be absolute path which require modifying according to your file system!!!

# Directory of your aligned RNA-seq data
sampleDir: /public1/data/projects/tumor/multi/TCGA/raw/RNA-Seq/BLCA
# Directory of your co-cleaned RNA-seq data
normalSampleDir: /public1/data/projects/tumor/multi/TCGA/raw/WXS/BLCA
# Directory to store your temporary files
tmpDir: /public1/tmp/lqh
# Our framework's working directory: stores all generated folders and files, chooses it with caution (large storage volume)
workDir: /home/lqh/Codes/Python/Integrative_Analysis_Bioinformatics_Pipeline/results

# Cancer type to analyze
cancerType: BLCA
# Sample type indicator
sampleType: Primary_Tumor
# Available num of cores
cores: 80

# Project-related sequencing data information
samples: /home/lqh/Codes/Python/Integrative_Analysis_Bioinformatics_Pipeline/tables/info/BLCA_RNA_somatic_calling_info.tsv
# Reference files for RNA-seq data co-cleaning and mutation calling
ref:
    # bed-format interval file for GENCODE v22 exon regions
    # change it with your own exon regions of interest
    # required columns: "chr", "start", "end", "exon_info", "count", "strand"
    exonInterval: /home/lqh/resources/database/gencode/GRCh38_GENCODE_v22_exon_rm_alt.bed
    # bed-format interval file for paired-normal Whole Exome Sequence(WES) targets, canonical for all TCGA projects.
    # change it with your own WES target interval file
    # required columns: "chr", "start", "end", "target_info", "strand"
    targetInterval: /home/lqh/resources/whole_exome_agilent_1.1_refseq_plus_3_boosters.targetIntervals_add_chr_to_hg38_rm_alt.bed
    # reference genome
    genome: /public1/data/resources/ref_genome/GRCh38/GRCh38.d1.vd1.fa
    # reference variants from public resources
    variant:
        # 1000 Human Genome project's SNP file
        kgSNP: /public1/data/resources/ref_variant/hg38/1000G_phase1.snps.high_confidence.hg38.vcf.gz
        # 1000 Human Genome project's INDEL file
        kgINDEL: /public1/data/resources/ref_variant/hg38/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
        # gnomad sites file with only AF (allele frequency) info
        gnomad: /home/lqh/resources/database/gnomad/af-only-gnomad.hg38.vcf.gz
        # gnomad sites file which was selected with chr1 SNP
        gnomad_SNP: /home/lqh/resources/database/gnomad/af-only-gnomad.GRCh38.SNP_biallelic_chr1_AF_mod.vcf.gz
    annotation:
        # GATK Funcotator's data source
        gatk_funcotator: /home/lqh/resources/database/gatk/funcotator_dataSources.v1.6.20190124s